openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Message service"
  description: "Message service"

servers:
  - url: http://localhost:8082

paths:
  /message/chat:
    post:
      description: Send message in the group chat
      parameters:
        - name: chat_id
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/ChatID"
        - name: text
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/Text"
        - name: user
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/UserID"
      responses:
        200:
          $ref: "#/components/responses/Message"
        400:
          $ref: "#/components/responses/BadRequest"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/InternalServerError"
    get:
      description: Get messages by chat id
      parameters:
        - name: id
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/ChatID"
      responses:
        200:
          $ref: "#/components/responses/MessageArray"
        400:
          $ref: "#/components/responses/BadRequest"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/InternalServerError"

components:
  schemas:
    UserID:
      description: User ID
      type: integer

    ChatUsers:
      description: Chat Users
      type: array
      items:
        $ref: "#/components/schemas/UserID"

    ChatID:
      description: Chat ID
      type: integer

    Text:
      description: Message text
      type: string

    Message:
      type: object
      properties:
        id:
          description: Message id
          type: integer
        chat_id:
          $ref: "#/components/schemas/ChatID"
        text:
          $ref: "#/components/schemas/Text"
        users:
          $ref: "#/components/schemas/ChatUsers"

    MessageArray:
      description: List of messages
      type: array
      items:
        $ref: "#/components/schemas/Message"

    Error:
      type: object
      properties:
        status:
          description: Error code
          type: integer
        detail:
          description: Human-readable error description
          type: string
        instance:
          description: Requested path
          type: string

  responses:
    Message:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Message"
    MessageArray:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MessageArray"
    ChatID:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ChatID"
    BadRequest:
      description: Request is incomplete
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    NotFound:
      description: Object not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    NotAllowed:
      description: Method is not allowed
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
