name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image cpp-poco
        run: docker compose build cpp-poco
      - name: Build the Docker image user-service
        run: cd lab2 && docker compose build user-service