name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image user-service
        run: docker build ./lab2 --file ./lab2/user-service.dockerfile --tag user-service:$(date +%s)
